name: Mikey 2 Times
favicon: null
layout_spectrum: 1
typography_spectrum: 0.39595
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6c3667'
    - '#89d31a'
    - '#1a0317'
    - '#ffffff'
    - '#b9b9b9'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
